### ISSUE TITLE
Final Group Capstone Project - Kanban Board Setup

### ISSUE THREAD

**Issue by katarighe** [katarighe/book-appointment-front-end#12]
Hello everyone, 😊

Here's our Kanban board for the final capstone group project. 

We've chosen a doctor-themed application for booking an appointment.

The number of teams that will be doing the capstone project is 5, here are the following names:

**Team member 1:** Mohamed Aden Ighe (@katarighe)
**Team member 2:** Antoine Makdessy (@ANTOINE1128)
**Team member 3:** Andry Narson (@rbd3)
**Team member 4:** Clarence Atim (@ClarenceAtim)
**Team member 5:** Sodeeq Olaide Awoyemi (@Errytagedesign)

**Link to the Kanban Board:** [www.github.com/users/katarighe/projects/4/views/1](http://www.github.com/users/katarighe/projects/4/views/1)

**Screenshot**

![image](https://github.com/katarighe/book-appointment-front-end/assets/80690364/9642791c-bdff-4aeb-b07d-76325067015a)

**Comment by Meltrust** [comment]
/
## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have descriptions, assignees, and pointings according to spec✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
